### ISSUE TITLE
Warnings when using `tibble`

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/ottr_docker#9]
We're updating the AnVIL books to use `jhudsl/base_otter:main` (they were still using `jhudsl/course_template:main`) and I'm getting some Warnings when using the `tibble` package:
```
Warning messages:
1: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘tibble’ 
2: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘tibble’ 
3: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘tibble’ 
4: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘pillar’ 
5: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘pillar’ 
6: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘pillar’
```

After a bit of investigating, here's what I know
- I confirmed by rendering locally on my computer, I get the warnings using `ottr_base:main` but not using `course_template:main`
- just running `library(tibble)` is sufficient to trigger the Warnings
- The `ellipses` package is deprecated and the functions should be imported from `rlang` going forward
- `tibble` switched from using `ellipses` to  using `rlang` as of `tibble` version `3.1.8`.  `ottr_base:main` uses version `3.0.3`, so is still using `ellipses`
- I don't know what is causing the Warning - how does it "know" to replace `ellipses` with `rlang`, if we've got an old version of `tibble`?

Edit: Just realized, when I render the book, I also see these exact warnings the first time I use `cow::borrow_chapter()` in a chapter.  Is it using `tibble` somewhere under the hood?

I'd try updating `tibble` to see if that removed the warnings, but I don't know how to build a Docker image :)

**Comment by avahoffman** [comment]
I wonder if updating the tidyverse image will help?

https://github.com/jhudsl/ottr_docker/blob/db34c6f264fd556c4001fa7616f9262493a2e781/base_ottr/Dockerfile#L1

**Comment by avahoffman** [comment]
So far, looks like rocker/tidyverse:4.2 addresses the tibble problem but causes some other weirdness in the TOC:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL/preview-69/docs/student-activity-guide.html#overview

**Comment by avahoffman** [comment]
A few too many dependencies when updating the rocker:tidyverse image. Saving that for another day.

installing `tibble` seems to fix the problem. Tested over on https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL/preview-69/docs/index.html and seems to be looking good.

**Comment by cansavvy** [comment]
Thanks for doing this @avahoffman !
